### ISSUE TITLE
Error running highstate after enabling in Pillars

### ISSUE THREAD

**Issue by racooper** [clinta/salt-pwgen#3]
Using your writeup at https://clinta.github.io/random-local-passwords/, I'm trying to implement the root password generator. Everything seems to set up fine, but when I try to run the highstate, I get an error:

> Rendering SLS 'root-pw' failed, render error: Jinja variable 'AliasedLoader' object has no attribute 'pwgen.get_pw'

I am running Salt 2015.5.10 from EPEL on CentOS 6 (for the master, python 2.6.6) and the minions are a mix of CentOS 6 and 7. Running a debug log on the Master, I am not seeing any calls to the extension directory, nor to the pwgen.py extension.  I'm sure I'm missing something, I just can't figure out what it is.

**Comment by clinta** [comment]
Did you check the link to the instructions on locating the master extension modules directory: https://docs.saltstack.com/en/latest/ref/configuration/master.html#extension-modules

The pwgen module needs to be installed in that location. You can either use the default, or customize the location in your salt master config.

**Comment by racooper** [comment]
well...it helps if I read the documentation on extension modules better.  actually ended up using module_dirs to set to my path and it works now.  Thanks!
